# Travis configuration for etl-schema.
#
# The steps it takes are:
#
#  * Run unit tests.
#  * install the Google Cloud SDK command line tools (gcloud)
#  * deploy the bigquery views when the branch/tag matches a supported
#    deployment target.
#
# NOTE: Cloud functions only support primitive IAM roles: Owner, Editor, Viewer.
# See: https://cloud.google.com/functions/docs/concepts/iam
# TODO(soltesz): Add deployment automation when fine-grained permissions are
# possible.
language: go

go:
- '1.13'

env:
- GO111MODULE=off

go_import_path: github.com/m-lab/etl-schema

before_install:
- go get github.com/mattn/goveralls
- echo Branch is ${TRAVIS_BRANCH} and Tag is $TRAVIS_TAG

script:
- set -e
- go test -v -short -covermode=count -coverprofile=merge.cov github.com/m-lab/etl-schema/cmd/bq_create_view
- goveralls -coverprofile=merge.cov -service=travis-ci
